### ISSUE TITLE
Add info on how to translate docs using Docusaurus

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-devdocs#109]
I removed the previous info as it was incorrect. Add it here: https://docs.yearn.finance/contributing/documentation/working-on-docs

**Comment by KurogeWashu** [comment]
Docusaurus localization tutorial https://docusaurus.io/docs/i18n/introduction
Tutorial for integrating CrowdIn https://docusaurus.io/docs/i18n/crowdin 
Example https://github.com/slorber/docusaurus-crowdin-example
Docusaurus' Crowdin translation dashboard https://crowdin.com/project/docusaurus-v2
Docusaurus' onboarding process for new translators https://github.com/facebook/docusaurus/issues/3526

**Comment by MarcoWorms** [comment]
started the infrastructure moves in order to tackle this issue!

https://github.com/yearn/yearn-devdocs/pull/137

**Comment by MarcoWorms** [comment]
As said in https://github.com/yearn/yearn-devdocs/pull/137#issuecomment-1119486951 we are not looking into translating the docs right now so I'll close this issue
