### ISSUE TITLE
Remove `@notice` from generated docs

### ISSUE THREAD

**Issue by fubuloubu** [yearn/yearn-devdocs#11]
![image](https://user-images.githubusercontent.com/3859395/120013768-2bcd7800-bfaf-11eb-9bb0-efb4a6beb7f3.png)

No reason to display this tag, it's what is used to generate that part of the docs already

**Comment by enie123** [comment]
@fubuloubu the changes I put in only work for the vyper files [changed the vyper template `contract.ejs`] -- I'll look into the solidity-docgen more to figure out how to make the changes for the solidity template `contract.hbs`
