### ISSUE TITLE
Update Kraken Info page

### ISSUE THREAD

**Issue by KurogeWashu** [yearn/yearn-devdocs#111]
Update with https://www.figma.com/file/ogHk3eGPgdhiIW3MuLeve5/kraken-edit?node-id=0%3A1

**Comment by jeffor12** [comment]
@KurogeWashu : hey, what is this issue about? I would like to update the kraken info page if you can provide me with more info :)

**Comment by KurogeWashu** [comment]
hey @jeffor12, thanks for reaching out. We are currently working with a contact from Kraken to update the pieces. 
The figma above is what we requested to have update. Please share if you have any comments on that

**Comment by jeffor12** [comment]
@KurogeWashu : I have made some slight changes, corrections and comments on the figma above. Maybe you can take a look.. :)
I general at least in my opinion the "What is yearn?" page seems to have a little to much information/text. but thats only my opinion :)

**Comment by KurogeWashu** [comment]
Thank you @jeffor12, we will take a look

**Comment by omgcorn** [comment]
Thank you @jeffor12 I'll make these changes. All of the Shiba content on there is just placeholder stuff that they'll have to create. Kraken's request to me was to summarize all changes we want to have made and to resubmit to them.

**Comment by jeffor12** [comment]
@omgcorn : allright! let me know if you need further help..cheers

**Comment by MarcoWorms** [comment]
I'm pinging @omgcorn to see how is this one going!
