### ISSUE TITLE
Fix error with Coingecko links

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-devdocs#123]
When checking Coingecko links using GH actions, it returns 503. Can it be fixed?

https://www.coingecko.com/en/coins/yearn-finance
https://www.coingecko.com/en/coins/vecrv-dao-yvault
https://www.coingecko.com/en/exchanges/curve#statistics

**Comment by KurogeWashu** [comment]
These are all working, would their servers have been overloaded that day? 
Closing for now. Let's create another issue if we want to use links to other statistics pages instead.
