### ISSUE TITLE
Fix metamask link that return 403

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-devdocs#124]
The tutorial to speed up a tx is returning 403, how can it be fixed?

Link: https://metamask.zendesk.com/hc/en-us/articles/360015489251-How-to-Speed-Up-or-Cancel-a-Pending-Transaction

**Comment by MarcoWorms** [comment]
Hey there! I couldn't reproduce this error, both links work here and doesn't return 403 when going to this page:

https://github.com/yearn/yearn-devdocs/blob/ae0d24cf96f92d123a0b632b112abae252ccc16e/docs/getting-started/using-yearn.md

and

https://docs.yearn.finance/getting-started/using-yearn#if-you-already-have-the-required-token-for-the-vault-that-you-would-like-to-deposit-in

are both linking correctly, no 403 here! Am I missing something?

**Comment by KurogeWashu** [comment]
Tested and working here as well.
