### ISSUE TITLE
Pin this repo on Yearn Github Org instead of the old "yearn-docs"

### ISSUE THREAD

**Issue by MarcoWorms** [yearn/yearn-devdocs#128]
Today at https://github.com/yearn we have the old "yearn-docs" docs pinned, we could change it and pin this one instead!

Pic of today's state:
![image](https://user-images.githubusercontent.com/7863230/148945784-0a1fcf03-65ee-4a88-93a0-63aa1f06b5c1.png)

**Comment by milkyklim** [comment]
![image](https://user-images.githubusercontent.com/10698619/148946565-ed3a6159-e90d-4fa9-a423-52fcc06b930d.png)
