### ISSUE TITLE
Grey border when searching

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-devdocs#132]
There's a grey border when searching and the window is between desktop and mobile. That line shouldn't be there. 

<img width="1055" alt="Screenshot 2022-01-12 at 18 07 47" src="https://user-images.githubusercontent.com/839844/149187960-b11f5a3e-8b76-4a68-9cfd-e2fb09718987.png">

**Comment by KurogeWashu** [comment]
reproduced in chrome
