### ISSUE TITLE
Change links to full URL instead of short links

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-devdocs#144]
Change links to full URL instead of short links.

Example:
/resources/faq#who-is-on-the-multisig => https://docs.yearn.finance/resources/faq#who-is-on-the-multisig

**Comment by MarcoWorms** [comment]
I didn't quite understand what to do on this issue, @saltyfacu can you give me more context please? 💃 ty!

**Comment by saltyfacu** [comment]
Yes, sure. The link in the docs are mostly relative, like this `/resources/faq#who-is-on-the-multisig`

We want to have them like this:` https://docs.yearn.finance/resources/faq#who-is-on-the-multisig`

I like relative links but the CI checks fail, and we are not able to check if some links are dead, because it always marks those links are dead

**Comment by MarcoWorms** [comment]
got it, thanks!!!
