### ISSUE TITLE
Add documentation on multisig members and their associations

### ISSUE THREAD

**Issue by bsamuels453** [yearn/yearn-devdocs#157]
The only references I found to multisig members in the docs was this security disclosure: https://docs.yearn.finance/security/index

There should be a dedicated page or a section on the [Governance and Operations](https://docs.yearn.finance/contributing/governance/governance-and-operations) that details:

1. Who is on the multisig
2. Their signing address
3. Their organization affiliation
4. An authenticated attestation that they are a multisig member and what their signing address is. This can be a twitter post declaring they are a multisig member, or some other form of evidence.

I believe this document has the most up to date information about the current multisig members, but more asking around might be necessary: https://gov.yearn.finance/t/yip-62-change-two-multisig-signers/10758

**Comment by saltyfacu** [comment]
Hey! Great comment! Would like to create that page?

**Comment by bsamuels453** [comment]
#164
