### ISSUE TITLE
Standarize Deployment to make it chain agnostic

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-devdocs#160]
Standarize [yearn-devdocs/DEPLOYMENT.md](https://github.com/yearn/yearn-devdocs/blob/master/docs/developers/v2/DEPLOYMENT.md) and make it chain agnostic

**Comment by MarcoWorms** [comment]
hey @saltyfacu would you like to make a draft for this one? Or do you have other docs I can look at to make this one? Thanks!

**Comment by MarcoWorms** [comment]
since v3 is coming around the corner we are not gonna tackle this issue now, but can be reopened whenever we want to tackle it again!
