### ISSUE TITLE
Bug: web infra picture out of date

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-devdocs#167]
![image](https://user-images.githubusercontent.com/38810205/160925499-d088b2f8-92c0-4782-b9a4-0bd024743886.png)

I don't believe we deploy the front end to ipfs anymore so the documentation is out of date

**Comment by DarkGhost7** [comment]
Maybe it will be live again soon? https://github.com/yearn/yearn-finance-v3/pull/464

**Comment by MarcoWorms** [comment]
I'm checking this one!

**Comment by MarcoWorms** [comment]
I talked to Dark Dhosty, Marius, Gambito, and Major, here is the current state of this issue:

- The current image is outdated (we don't use IPFS)
- The current flow is not public

I don't know if this is much of a priority, but next steps in my opinion would be creating a private updated doc (we don't have a formal structure for private docs afaik) and remove the outdated content form public docs
