### ISSUE TITLE
Add YIP-66 mechanics to docs

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-devdocs#170]
https://gov.yearn.finance/t/yip-66-streamlining-contributor-compensation/12247

**Comment by banteg** [comment]
also add info about usage of llamapay
https://llamapay.io/streams?chainId=1&address=ychad.eth

**Comment by MarcoWorms** [comment]
I think this requires us first documenting veYFI first from what I've read since it depends on YIP 65, I opened an issue to do that first then I come back to this one
