### ISSUE TITLE
Add in reasoning for why buying on Sushiswap is done - less slippage / easy way to trade in and out

### ISSUE THREAD

**Issue by defiglenn** [yearn/yearn-devdocs#183]
docs/getting-started/guides/how-boost-works.md

**Comment by MarcoWorms** [comment]
I thought this was explained by the following sentence "This is because Yearn and its users provide liquidity on Sushiswap", where can I check if sushiwap has less slippage for this case? seems like could be any other dex as long as yearn provides liquidity there but I might be wrong!

**Comment by shakibaei65** [comment]
sghl vlc k'hvdvd  ';jsdn

**Comment by saltyfacu** [comment]
We are moving towards ySwaps. This is not relevant anymore.
