### ISSUE TITLE
Add follow up data for the risk framework

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-devdocs#204]
This is great follow up data for a potential risk score per vault:
https://github.com/yearn/yearn-data-analytics/blob/master/vault-risk.md

**Comment by kyhoon** [comment]
https://github.com/yearn/yearn-data-analytics/tree/master/src/risk_framework
this is the new link for the description!
sorry for the inconvenience, the repo is currently undergoing quite a lot of change, I will follow up on this issue and update the link whenever it changes
