### ISSUE TITLE
To add page for detailed APY calculation explanation

### ISSUE THREAD

**Issue by JKtranslator** [yearn/yearn-devdocs#206]
# How Yearn calculates its yVaults Returns

It is a standard on Defi Space to estimate returns through [APY](https://www.investopedia.com/terms/a/apy.asp) and [APR](https://www.investopedia.com/terms/a/apr.asp), and Yearn also does so. However, different calculations depend on the yVault underlying asset. One for [Curve.Finance](https://curve.fi/) LP Tokens and another way for non-curve assets. For a simpler version, check the [TL;DR version](https://medium.com/iearn/how-yearn-calculates-estimated-returns-apy-b4fd5b687bf9) or the infographic at the end of the page. The following sections will show how each one is calculated:

## Non-curve assets

The estimated returns are displayed on Yearn.finance this way:
 
![image](https://user-images.githubusercontent.com/88235023/169620809-178dabd0-82f4-4304-bf13-285577c5b509.png)

Where the definition of each one is:
•	**Gross APR:** Vault total APR before deducted fees
•	**Net APY:** Vault considered APY. If the network is ETH mainnet, this will show the Monthly APY, as the harvests are not that frequent. On the other hand, if the network is Fantom, then the Weekly API is chosen, as the harvests are more frequent.
•	**Weekly APY:** Calculated considering the yVault price share difference in the last seven days
•	**Monthly APY:** Calculated considering the yVault price share difference in the last 30 days
•	**Inception APY:** Calculated considering the yVault price share difference since inception

The actual code can be found [on this repo](https://github.com/yearn/yearn-exporter/tree/master/yearn/apy)

![image](https://user-images.githubusercontent.com/88235023/169621180-8febc13c-c24e-4509-9b5b-b14ec8271293.png)

Where the file that contains the calculation for the most recent version of the yVaults [is this one](https://github.com/yearn/yearn-exporter/blob/master/yearn/apy/v2.py)

## Curve assets
The estimated returns are displayed on Yearn.finance this way:

 ![image](https://user-images.githubusercontent.com/88235023/169621208-511af49a-42f6-4487-99b1-abc329c69601.png)

Where the definition of each one is:
•	Pool APY: APY is calculated considering the change in the “virtual price” of the curve.finance LP token in the last seven days.
•	Bonus Rewards APR: Rewards are usually given by the token owner. IE frax curve pools also offer frax as a reward. The APY if the token were sold at the current price.
•	Base CRV APR: The APR from the CRV emissions this curve pool gets. 
•	Boost: Multiplier from staked veCRV, ranging from 1x to 2.5x
•	Convex APR: APR when the yVault strategy is depositing the curve.finance LP tokens into [Convex Finance](https://www.convexfinance.com/)
•	Gross APR: Vault total APR before deducted fees
•	Net APY: Vault current APY, after deducting the fees

The actual code can be found [on this repo](https://github.com/yearn/yearn-exporter/tree/master/yearn/apy/curve)
 
![image](https://user-images.githubusercontent.com/88235023/169621414-19d1301a-9785-4c37-8884-13c603a3a9ce.png)

Where the file that contains the calculation for the most recent version of the yVaults [is this one](https://github.com/yearn/yearn-exporter/blob/master/yearn/apy/curve/simple.py)

### Notes:

•	When the active strategy of a yVault uses Convex Finance, and the streaming of the rewards is frozen at Convex, Yearn.finance Net APY will show 0% until the streaming is resumed.
 
![image](https://user-images.githubusercontent.com/88235023/169621457-995c8bf6-f4e2-42d3-ae31-48fae6fd2b5a.png)

More details about rewards streaming on [Convex Finance](https://docs.convexfinance.com/) 

•	When there is a spike of transactions in a pool, the “Pool APY” will reflect it for a week, as the fees will be added to the “virtual price” of this pool, and the calculation takes the last seven days into account.

## Infographic

![image](https://user-images.githubusercontent.com/88235023/169621669-11a8b974-c3a4-4a44-8134-3074ea19e75a.png)

**Comment by saltyfacu** [comment]
Nice description! Would you mind sending a PR as a docs page so we include it in the documentation?

**Comment by JKtranslator** [comment]
Sure! https://docs.google.com/document/d/17fNl5N1UTTE8O7VA2iZQLaO1t54z4cZ_aTUqDTyxM_c/edit?usp=sharing
