### ISSUE TITLE
Highlight links somehow

### ISSUE THREAD

**Issue by fameal** [yearn/yearn-devdocs#33]
In the image below, partners.py is a link. I cannot distinguish a link from regular text.

<img width="966" alt="Screenshot 2021-08-23 at 14 48 25" src="https://user-images.githubusercontent.com/839844/130449760-6f5bfbaf-27a9-4016-a870-18fb7f182618.png">

**Comment by pandadefi** [comment]
Have you tried to play around with https://docusaurus.io/docs/styling-layout ?

**Comment by fameal** [comment]
fixed
