### ISSUE TITLE
add kong

### ISSUE THREAD

**Issue by MarcoWorms** [yearn/yearn-devdocs#374]
https://kong-one.vercel.app/

**Comment by ATREAY** [comment]
Hey @MarcoWorms, Would you please provide more details on the exact location for inserting this link and instructions for addressing the issue?

**Comment by MarcoWorms** [comment]
take a look at the /docs folder and the sidebars and propose one, I can help you once the PR is up to fit in the proper place!

**Comment by 0xBasically** [comment]
Kong is pretty experimental and not fully working on eth much less all chains yearn is on, we can add it when it is more out of alpha stage. Seafood is a good replacement for other services being deprecated at this time I think.
