### ISSUE TITLE
Add 0.4.3 version of smart contracts

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-devdocs#43]
Right now we only have 0.4.2. It'd be great to have 0.4.3

**Comment by pandadefi** [comment]
> Not sure if I am running vydoc correctly, only outputs when are vault.md and registry.md files when running:
> `vydoc -i contracts -o docs -c vyper -f markdown`
> 
> @pandadefi is this what should happen?

Yes only two files are vyper files

**Comment by pandadefi** [comment]
You must generate the solidity doc using yarn
