### ISSUE TITLE
Developers review

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-devdocs#44]
- [ ] URL: https://yearn.github.io/yearn-devdocs/v2/process-and-procedures/emergency
	- [ ] TLDR ==> TL;DR
	- [x] [CMO](https://github.com/yearn/chief-multisig-officer) add a comment that is a private repo
	- [x] [strategists-ms](https://github.com/yearn/strategist-ms) add a comment that is a private repo
- [x] URL: https://yearn.github.io/yearn-devdocs/v2/process-and-procedures/naming-convention
	- [x] `yVaults` is not rendered as title. Maybe because it doesn't have content below
- [ ] URL: https://yearn.github.io/yearn-devdocs/v2/yearn-sdk/yearn-stack
	- [ ] The first image: can we get a better one? Like the one in [Yearn Lens](https://yearn.github.io/yearn-devdocs/v2/yearn-lens/yearn-lens)
- [x] URL: https://yearn.github.io/yearn-devdocs/v2/yearn-lens/contracts
	- [x] `Mainnet` is not rendered as title. Maybe because it doesn't have content below

**Comment by KurogeWashu** [comment]
updated all points, except for flow chart render. Do we know who has the original file and where the one in Yearn Lens was produced?
