### ISSUE TITLE
fix: Missing supported chain

### ISSUE THREAD

**Issue by matteoettam09** [yearn/yearn-devdocs#440]
Looking into vaults v2 I notice there is support also for the BASE chain, which is not mentioned here:

https://docs.yearn.fi/getting-started/using-yearn#yearn-is-multi-chain

I would consider adding it.
Thanks.

**Comment by rossgalloway** [comment]
Thanks for the suggestion. I have added the change to #437, which updates that walkthrough and adds a new one for V3

**Comment by rossgalloway** [comment]
fixed in #437. @MarcoWorms we can close this
