### ISSUE TITLE
Resources review

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-devdocs#46]
- [x] URL: https://yearn.github.io/yearn-devdocs/resources/links
	- [x] [Learn Yearn](https://www.learnyearn.finance/): dead. remove
	- [x] -   [Yearn API](https://vaults.finance/all) => https://api.yearn.finance/v1/chains/1/vaults/all
	- [x] [yCosystem](https://yfi.fyi/) outdated. remove.
	- [x] [Yearn ROI Calc](https://yearn-roi.xyz/) dead. remove
	- [x] [Yieldfarming](https://yieldfarming.info/) outdated remove
- [x] URL: https://yearn.github.io/yearn-devdocs/resources/financials
	- [x] We can link directly to the repo with all reports.
- [x] URL: https://yearn.github.io/yearn-devdocs/resources/risks/strategy-risks
	- [x] Remove ``## Strategy Scoring System`

**Comment by KurogeWashu** [comment]
Updated via:
- [ x] https://github.com/yearn/yearn-devdocs/pull/47/commits/fb76c225a881da05f62df1a28da631a4c50bfed6
- [ x] https://github.com/yearn/yearn-devdocs/pull/47/commits/e4f6b92d79d025baddc61a7f8e22bf0d5706da1d
- [ x] https://github.com/yearn/yearn-devdocs/pull/47/commits/1321d0b012cf9b8b3a9dbb2354c6893f47de1d07
for the last point, did you mean to delete the entire section or do we still want the link to the initial scoring system?

**Comment by saltyfacu** [comment]
re: `## Strategy Scoring System`

it said something like "this is a first attempt to do..." and a google doc. We use something different right now that is not public but we may want to share screenshots. It's something that we need to write from scratch. 

What do you think?
