### ISSUE TITLE
Strategy Scoring System

### ISSUE THREAD

**Issue by KurogeWashu** [yearn/yearn-devdocs#49]
To continue on last point of #46

**Comment by KurogeWashu** [comment]
This is an older document on strategy scoring https://docs.google.com/document/d/18M2eJNsshKJlIAD_dSVGfMvTkIgZYJzXjT538QSmALo/edit

**Comment by saltyfacu** [comment]
I sent this to the security team for them to check it out

**Comment by saltyfacu** [comment]
The doc is outdated. This is how we score now: https://hackmd.io/sFt1tJ8pRgeDJ-Uz7tnR2A?view

**Comment by saltyfacu** [comment]
This became risk scoring. I'll close this as it's not relevant anymore.
