### ISSUE TITLE
Update Flow Chart Image

### ISSUE THREAD

**Issue by KurogeWashu** [yearn/yearn-devdocs#50]
References #44

- [x] URL: https://yearn.github.io/yearn-devdocs/v2/yearn-sdk/yearn-stack

- - [x] The first image: can we get a better one? Like the one in Yearn Lens

**Comment by KurogeWashu** [comment]
Updated via f3c0ac828a91f14e50c3e6c2b2f129a5ac6d75ca

Used gray #999999 for the lines helps with compatibility in dark mode. 

will also need to update the flow chart in yearn-lens - seems one of the graphs in lens.drawio is non-editable (the one on the bottom right). Do we want them both on the page?

**Comment by KurogeWashu** [comment]
New link: https://yearn.github.io/yearn-devdocs/vaults/yearn-sdk/yearn-stack

**Comment by saltyfacu** [comment]
the background is still grey :/ Can you remove it?

**Comment by KurogeWashu** [comment]
@saltyfacu The previous draw.io file didn't contain the image, I've added transparency to make it look better. Would need to re-draw the graph if we don't have the original.

**Comment by KurogeWashu** [comment]
Recreated Frontend Stack image for light / dark mode https://i.imgur.com/aWRSK5p.png

This should be the last of it
