### ISSUE TITLE
Improve CRV vote locking, yveCRV and yvBOOST articles

### ISSUE THREAD

**Issue by saltyfacu** [yearn/yearn-devdocs#55]
URL: [https://yearn.github.io/yearn-devdocs/getting-started/guides/how-to-understand-crv-vote-locking](https://yearn.github.io/yearn-devdocs/getting-started/guides/how-to-understand-crv-vote-locking) can we improve this with qosmonot's article?

Article: https://medium.com/iearn/thats-boost-folks-7afae75db826

**Comment by saltyfacu** [comment]
this has to go to the versioned docs

**Comment by KurogeWashu** [comment]
Updated via 67e37505cf046466d750ce10ad773dff02f1d917
