### ISSUE TITLE
Add IronBank to docs

### ISSUE THREAD

**Issue by KurogeWashu** [yearn/yearn-devdocs#94]
https://github.com/CreamFi/compound-protocol/tree/cream-v2

**Comment by KurogeWashu** [comment]
Intro with https://creamdotfinance.medium.com/introducing-the-iron-bank-bab9417c9a

**Comment by defiglenn** [comment]
Summarising the above:
Products - Iron Bank
The Iron Bank provides a lending service both to users and protocols. For protocols that are whitelisted this can be zero-collateral loans. For users, this will be an overcollateralised loan. For example, you deposit 1 ETH and can withdraw approximately half its value in a stablecoin. Innovations in the future may see the collateralisation rate for users fall.

**Comment by KurogeWashu** [comment]
added via 861ef7e134d20906013388d288101c231ae45f54
